### ISSUE TITLE
名称有办法翻译过来吗

### ISSUE THREAD

**Issue by caifenglin** [liulei901112/txkt_m3u8.sqlite_ts#1]
视频名称有办法解析过来吗

**Comment by liulei901112** [comment]
m3u8.sqlite文件只是包涵了0-1000,1001-2000这样的ts数据片段，并没有对应课程章节名称的信息，所以我也没办法解析出来。
不过最近我有个想法检查下所有的数据，看看能不能找到对应的课程URL，访问URL解析html获取课程名称。不过只是想法，还得试试，而且可能比没有。这个文件可能单纯的只是个数据文件，通过文件名（ID）关联到另一张课程章节名称信息的表在网页上显示的。理论上从软件设计的角度也不会把这个信息放在数据文件上。

**Comment by liulei901112** [comment]
> 视频名称有办法解析过来吗

m3u8.sqlite文件只是包涵了0-1000,1001-2000这样的ts数据片段，并没有对应课程章节名称的信息，所以我也没办法解析出来。
不过最近我有个想法检查下所有的数据，看看能不能找到对应的课程URL，访问URL解析html获取课程名称。不过只是想法，还得试试，而且可能比没有。这个文件可能单纯的只是个数据文件，通过文件名（ID）关联到另一张课程章节名称信息的表在网页上显示的。理论上从软件设计的角度也不会把这个信息放在数据文件上。
